amazon/urls.py
from django.urls import path
from . import views
from django.contrib import admin
from django.contrib.auth import views as django_auth_views

app_name = 'amazon'

urlpatterns = [
    path('lp/', views.Lp.as_view(), name='lp'),
    path('items/', views.ItemList.as_view(), name = 'item_list'),
    path('item/<int:pk>', views.ItemDetail.as_view(), name = 'item_detail'),
    path('', views.Login.as_view(), name = "login"),
    path('logout', django_auth_views.LogoutView.as_view(), name = "logout"),
    path('sign_up/', views.SignUp.as_view(), name='sign_up'),
    path('sign_up/done/<token>', views.SignUpDone.as_view(), name='sign_up_done'),
    path('cart/<int:pk>', views.ShoppingCartDetail.as_view(), name = 'cart'), #[7-4]追加
    path('ajax_amount/', views.update_cart_item_amount, name = 'update_cart_item_amount'),#[7-4]追加
    path('ajax_delete/', views.delete_cart_item, name = 'delete_cart_item'),#[7-4]追加
]

config/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('amazon.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

amazon/models/cart.py
from django.db import models
from django.db.models import F, Sum
from django.contrib.auth import get_user_model
from ..models import Product

User = get_user_model()


class ShoppingCart(models.Model):

    user = models.OneToOneField(
        User,
        verbose_name = 'ユーザ',
        related_name = 'cart',
        on_delete = models.CASCADE
    )
    @property
    def item_count(self):
        return self.cart_items.all().aggregate(amount = Sum('amount'))['amount']
    @property
    def total_price(self):
        return self.cart_items.all().aggregate(total=Sum(F('product__price') * F('amount')))['total']


class ShoppingCartItem(models.Model):
    cart = models.ForeignKey(
        ShoppingCart,
        related_name = 'cart_items',
        verbose_name = 'ショッピングカート',
        on_delete = models.CASCADE
    )
    product = models.ForeignKey(
        Product,
        verbose_name = '商品',
        on_delete = models.CASCADE
    )
    amount = models.IntegerField(
        verbose_name = '数量'
    )

amazon/models/product.py
from django.db import models

class Product(models.Model):
    class Meta:
        verbose_name = '商品'
        verbose_name_plural = "商品"

    thumbnail = models.ImageField(
        verbose_name = 'サムネイル',
        upload_to = "thumbnails/"
    )

    name = models.CharField(
        verbose_name = '名前',
        max_length=150,
        null = False,
        blank=False
    )
    price = models.IntegerField(
        verbose_name = '価格'
    )
    description = models.TextField(
        verbose_name = '説明'
    )

amazon/forms/user.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from ..models import *
from django.core.exceptions import ValidationError
from django.contrib.auth import get_user_model

User = get_user_model()


class LoginForm(AuthenticationForm):
    """ログインフォーム"""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label


class SignUpForm(UserCreationForm):
    """ユーザー登録用フォーム"""

    class Meta:
        model = User
        fields = ('email', 'name',)
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label  # placeholderにフィールドのラベルを入れる

amazon/views/cart.py
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect, JsonResponse, HttpResponseBadRequest
from ..models import Product, ShoppingCart, ShoppingCartItem
from django.urls import reverse


class ShoppingCartDetail(LoginRequiredMixin, generic.DetailView):
    model = ShoppingCart
    template_name = "amazon/shopping_cart.html"

    def post(self, request, *args, **kwargs):
        user = request.user
        product_pk = request.POST.get('product_pk')
        product = Product.objects.get(pk = product_pk)
        amount = request.POST.get('amount')

        exist = ShoppingCartItem.objects.filter(cart__user = user).filter(product = product)

        # すでにカートに存在する商品の場合は個数をインクリメント
        if len(exist) > 0:
            current_amount = exist[0].amount
            exist[0].amount = current_amount + int(amount)
            exist[0].save()
        else:
            new_cart_item = ShoppingCartItem()
            new_cart_item.cart = request.user.cart
            new_cart_item.product = product
            new_cart_item.amount = int(amount)
            new_cart_item.save()
        return HttpResponseRedirect(reverse('amazon:cart',  kwargs={'pk': self.get_object().pk}))


def update_cart_item_amount(request):
    cart_item_pk = request.POST.get('cart_item_pk')
    new_amount = request.POST.get('amount')

    if cart_item_pk == None or new_amount == None:
        return JsonResponse({'error': 'invalid parameter'})
    if int(new_amount) <= 0:
        return JsonResponse({'error': 'amount must be greater than zero'})
    
    try:
        cart_item = ShoppingCartItem.objects.get(pk = cart_item_pk)
        cart_item.amount = int(new_amount)
        cart_item.save()
        print(cart_item.amount)
        return JsonResponse({'success': True})
    except Exception as e:
        return JsonResponse({'error': str(e.args)})


def delete_cart_item(request):
    cart_item_pk = request.POST.get('cart_item_pk')
    if cart_item_pk == None:
        return JsonResponse({'error': 'invalid parameter'})
    try:
        cart_item = ShoppingCartItem.objects.get(pk = cart_item_pk)
        cart_item.delete()
        return JsonResponse({'success': True})
    except Exception as e:
        return JsonResponse({'error': str(e.args)})

amazon/views/item.py
from ..models import Product
from django.views import generic


class ItemList(generic.ListView):
    model = Product
    template_name = 'amazon/item_list.html'
    def get_queryset(self):
        products = Product.objects.all()
        if 'q' in self.request.GET and self.request.GET['q'] != None:
            q = self.request.GET['q']
            products = products.filter(name__icontains = q)

        return products


class ItemDetail(generic.DetailView):
    model = Product
    template_name = 'amazon/item_detail.html'

amazon/views/lp.py
from django.views import generic

class Lp(generic.TemplateView):
    template_name = 'amazon/lp.html'

amazon/views/user.py
from django.views import generic
from django.contrib.auth.views import LoginView
from ..forms import *
from django.http import HttpResponseRedirect, JsonResponse, HttpResponseBadRequest #[6-4]追加
from django.core.signing import BadSignature, SignatureExpired, dumps, loads #[6-4]追加
from django.urls import reverse #[6-4]追加
from django.contrib.sites.shortcuts import get_current_site #[6-4]追加
from django.template.loader import get_template #[6-4]追加
from django.contrib import messages #[6-4]追加
from django.conf import settings
from ..models import ShoppingCart


class Login(LoginView):
    """ログインページ"""
    form_class = LoginForm
    template_name = 'amazon/login.html'


class SignUp(generic.CreateView):
    """ユーザー仮登録"""
    template_name = 'amazon/sign_up.html'
    form_class = SignUpForm
   
    def form_valid(self, form):
        """仮登録と本登録用メールの発行."""
        # 仮登録と本登録の切り替えは、is_active属性を使うと簡単です。
        # 退会処理も、is_activeをFalseにするだけにしておくと捗ります。
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        # アクティベーションURLの送付
        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': self.request.scheme,
            'domain': domain,
            'token': dumps(user.pk),
            'user': user,
        }

        subject_template = get_template('amazon/mail_template/sign_up/subject.txt')
        subject = subject_template.render(context)

        message_template = get_template('amazon/mail_template/sign_up/message.txt')
        message = message_template.render(context)

        user.email_user(subject, message)
        messages.success(self.request, '本登録用リンクを送付しました')
        return  HttpResponseRedirect(reverse('amazon:sign_up'))


class SignUpDone(generic.TemplateView):
    """メール内URLアクセス後のユーザー本登録"""
    template_name = 'amazon/sign_up_done.html'
    timeout_seconds = getattr(settings, 'ACTIVATION_TIMEOUT_SECONDS', 60*60*24)  # デフォルトでは1日以内

    def get(self, request, **kwargs):
        """tokenが正しければ本登録."""
        token = kwargs.get('token')
        try:
            user_pk = loads(token, max_age=self.timeout_seconds)

        # 期限切れ
        except SignatureExpired:
            return HttpResponseBadRequest()

        # tokenが間違っている
        except BadSignature:
            return HttpResponseBadRequest()

        # tokenは問題なし
        else:
            try:
                user = User.objects.get(pk=user_pk)
            except User.DoesNotExist:
                return HttpResponseBadRequest()
            else:
                if not user.is_active:
                    # 問題なければ本登録とする
                    user.is_active = True
                    user.save()

                    his_cart = ShoppingCart()
                    his_cart.user = user
                    his_cart.save()

                    return super().get(request, **kwargs)

        return HttpResponseBadRequest()

amazon/templates/amazon/base.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">
    
    <link href="{% static 'css/base.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet" media="only screen and (max-width: 1200px)" />
    <script src="{% static 'js/script.js' %}" type="text/javascript"></script>

    <title>techpit amazon</title>
</head>
<body>
    <header class="section-header">
        <section class="header-main">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-md-3">
                    <a href="{% url 'amazon:lp' %}">
                        <div class="brand-wrap">
                            <img class="logo" src="{% static 'images/logo-dark.png' %}">
                            <h2 class="logo-text">Techpit amazon</h2>
                        </div> <!-- brand-wrap.// -->
                    </a>
                    </div>
                    <div class="col-lg-6 col-sm-6">
                        <form method= "get" action="{% url 'amazon:item_list' %}" class="search-wrap">
                            <div class="input-group">
                                <input name="q" type="text" class="form-control" placeholder="Search">
                                <div class="input-group-append">
                                    <button id="id_search_button" class="btn btn-warning" type="submit">
                                    <i class="fa fa-search"></i>
                                    </button>
                                </div>
                            </div>
                        </form> <!-- search-wrap .end// -->
                    </div> <!-- col.// -->
                    <div class="col-lg-3 col-sm-6">
                        <div class="widgets-wrap d-flex justify-content-end">
                            {% if user.is_authenticated %}
                            <div class="widget-header icontext">
                                <a href="{% url 'amazon:cart' user.cart.pk %}" class="icontext">
                                    <div class="icon-wrap icon-sm bg2 round text-secondary"><i class="fa fa-shopping-cart"></i></div>
                                    <div class="text-wrap">
                                        <small>カート</small>
                                        <span>{{ user.cart.item_count|default_if_none:"0" }}商品</span>
                                    </div>
                                </a>
                            </div> <!-- widget .// -->
                            {% endif %}
                            <div class="widget-header icontext">
                                <div class="icon-wrap icon-sm bg2 round text-secondary"><i class="fa fa-user"></i></div>
                                <div class="text-wrap">
                                    {% if user.is_authenticated %}
                                    <small>{{user.name}}さん</small>
                                    <span><a href="{% url 'amazon:logout' %}">Logout</a></span>
                                    {% else %}
                                    <small>ゲスト</small>
                                    <span><a href="{% url 'amazon:login' %}">Login</a></span>
                                    {% endif %}
                                </div>
                            </div> <!-- widget  dropdown.// -->
                        </div>	<!-- widgets-wrap.// -->	
                    </div> <!-- col.// -->
                </div> <!-- row.// -->
            </div> <!-- container.// -->
        </section> <!-- header-main .// -->
    </header> <!-- section-header.// -->
    <div class="container" style="padding: 2rem">
            {% block content %}{% endblock %}
    </div>
    <footer class="section-footer bg2">
        <div class="container">
            <section class="footer-bottom row">
                
                <div class="col-sm-12">
                    <p class="text-sm-right">
    Copyright © 2019 
    <a href="#">Techpit</a>
                    </p>
                </div>
            </section> <!-- //footer-top -->
        </div><!-- //container -->
    </footer>
    
        {% block scripts %}{% endblock %}
</body>
</html>

amazon/templates/amazon/item_detail.html
{% extends "amazon/base.html" %}
{% block content %}
{% load static %}
<main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">
        <div class="row wow fadeIn">
            <div class="col-md-6 mb-4">
                <img src="{{ object.thumbnail.url }}" class="img-fluid" alt="">
            </div>
            <div class="col-md-6 mb-4">
                <div class="p-4">
                    <div class="mb-3">
                        <a href="">
                        <span class="badge purple mr-1">Category 2</span>
                        </a>
                        <a href="">
                        <span class="badge blue mr-1">New</span>
                        </a>
                        <a href="">
                        <span class="badge red mr-1">Bestseller</span>
                        </a>
                    </div>
                    <p class="lead">
                        <h2>{{ object.name }}</h2>
                        <span>¥{{ object.price }}</span>
                    </p>
                    <p class="lead font-weight-bold">商品説明</p>
                    <p>{{ object.description }}</p>
                    {% if user.is_authenticated %}
                    <form method="post" action="{% url 'amazon:cart' user.cart.pk %}" class="d-flex justify-content-left">
                        {% csrf_token %}
                        <!-- Default input -->
                        <input name="product_pk" type="hidden" value="{{ object.pk }}">
                        <input name="amount" type="number" value="1" aria-label="Search" class="form-control" style="width: 100px; margin-right: 1rem">
                        <button class="btn btn-primary btn-md my-0 p" type="submit">Add to cart
                        <i class="fas fa-shopping-cart ml-1"></i>
                        </button>
                    </form>
                    {% endif %}
                </div>
            </div>
        </div>
        <hr>
        <div class="row d-flex justify-content-center wow fadeIn">

            <div class="col-md-6 text-center">

                <h4 class="my-4 h4">Additional information</h4>

                <p>
                    Djangoのようなフレームワークを利用しても、ページのデザインを綺麗にすることはできません。
                    恐らくこの教材で学習している方のほとんどがどちらかというとサーバサイドを勉強している方が多いのかと思慮しますので、
                    htmlやcssの部分はあまり得意でないという方が多いと思います。そのような方はぜひBootstrap等のCSSフレームワークを利用することをお勧めします。
                    また、コードのスニペットをネット上から拝借するのも非常に良いと思います。日本の
                    サイトですとまだこのスニペットのまとめサイトのようなものは少ないですが、海外ですと無数に存在するので、ぜひそれらを活用していただくことをお勧めします。(無料で公開されていることろが多いです)
                    特にログイン画面やサインアップ部分は「bootstrap login snippet」等で検索するといろいろな方が作成したスニペットが出てくるので、是非今後「自分でサービス開発したい！」となった際にご参考にしていただければと思います。
                </p>
            </div>
        </div>
        <div class="row wow fadeIn">
            <div class="col-lg-4 col-md-12 mb-4">
                <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

            </div>
            <div class="col-lg-4 col-md-6 mb-4">
                <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">
            </div>
            <div class="col-lg-4 col-md-6 mb-4">
                <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

            </div>
        </div>
    </div>
</main>
{% endblock %}

amazon/templates/amazon/item_list.html
{% extends "amazon/base.html" %}
{% block content %}
{% load static %}
    <div class="row-sm">
    {% for object in object_list %}
        
        <div class="col-md-3">
            <figure class="card card-product">
                <div class="img-wrap"> <img src="{{ object.thumbnail.url }}"></div>
                    <figcaption class="info-wrap">
                        <h6 class="title "><a href='{% url 'amazon:item_detail' object.pk %}'>{{ object.name }}</a></h6>
                        
                        <div class="price-wrap">
                            <span class="price-new">{{ object.price }}円</span>
                        </div> <!-- price-wrap.// -->
                    
                </figcaption>
            </figure> <!-- card // -->
        </div> <!-- col // -->
        
    {% endfor %}
    </div>
{% endblock %}

amazon/templates/amazon/login.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>  
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">
    <title>title here</title>
</head>
<body style="background: teal"">
    <div class="container" style="padding: 2rem">
        <div class="row">
            <div class="col-md-6 offset-md-3 col-12">
                <div class="card bg-light">
                    <div class="card-body mx-auto">
                        <form action="" method="post">
                            {{ form.non_field_errors }}
                            <div class="input-group form-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-envelope"></i></span>
                                </div>
                                {{ form.username }}
                            </div>
                            {{ form.email.errors }}
        
                            <div class="input-group form-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-lock"></i></span>
                                </div>
                                {{ form.password }}
                            </div>
                            {{ form.password.error }}
                            {% csrf_token %}
                            <div class="form-group">
                                <button type="submit" name="btn" value="Login" class="btn btn-primary btn-block">Login</button>
                            </div>
                            <p class="text-center">アカウントをお持ち出ないですか? <a href="{% url 'amazon:sign_up' %}">Sign up</a> </p>                                                               
                        </form>
                    </div> <!-- card body -->
                </div> <!-- card  -->
            </div>
        </div>
    </div>
</body>
</html>

amazon/templates/amazon/lp.html
{% extends "amazon/base.html" %}
{% block content %}
{% load static %}
    <link href="{% static 'plugins/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'plugins/owlcarousel/assets/owl.theme.default.css' %}" rel="stylesheet">
    <script src="{% static 'plugins/owlcarousel/owl.carousel.min.js' %}"></script>
  
    <section class="section-main bg padding-top-sm">
        <div class="container">
            <div class="row-sm">
                <div class="col-md-8">
                   <div class="owl-init slider-main owl-carousel" data-items="1" data-dots="false" data-nav="true">
                        <div class="item-slide">
                            <a href="{% url 'amazon:item_list' %}">
                                <img src="{% static 'images/banners/slide1.jpg' %}">
                            </a>
                        </div>
                        <div class="item-slide rounded">
                            <a href="{% url 'amazon:item_list' %}">
                                <img src="{% static 'images/banners/slide2.jpg' %}">
                            </a>
                        </div>
                        <div class="item-slide rounded">
                            <a href="{% url 'amazon:item_list' %}">
                                <img src="{% static 'images/banners/slide3.jpg' %}">
                            </a>
                        </div>
                    </div>
                </div> <!-- col.// -->
                <aside class="col-md-4">
                    <div class="card mb-3">
                        <figure class="itemside">
                            <div class="aside"><div class="img-wrap p-2 border-right"><img class="img-sm" src="{% static 'images/items/1.jpg' %}"></div></div>
                            <figcaption class="text-wrap align-self-center">
                                <h6 class="title">Group of products is here </h6>
                                <a href="#">More items</a>
                            </figcaption>
                        </figure>
                    </div> <!-- card.// -->
                    <div class="card mb-3">
                        <figure class="itemside">
                            <div class="aside"><div class="img-wrap p-2 border-right"><img class="img-sm" src="{% static 'images/items/2.jpg' %}"></div></div>
                            <figcaption class="text-wrap align-self-center">
                                <h6 class="title">Group of products  is here </h6>
                                <a href="#">More items</a>
                            </figcaption>
                        </figure>
                    </div> <!-- card.// -->
                    
                    <div class="card">
                        <figure class="itemside">
                            <div class="aside"><div class="img-wrap p-2 border-right"><img class="img-sm" src="{% static 'images/items/3.jpg' %}"></div></div>
                            <figcaption class="text-wrap align-self-center">
                                <h6 class="title">Group of products is here </h6>
                                <a href="#">More items</a>
                            </figcaption>
                        </figure>
                    </div> <!-- card.// -->
                </aside>
            </div>
        </div> <!-- container .//  -->
    </section>
    <section class="section-content padding-y bg">
        <div class="container">
        
            <div class="card">
                <div class="card-body">
            
                    <header class="section-heading">
                        <h3 class="title-section">Django Amazon</h3>
                    </header>
                    
                    <article>
                        <p>
                            この教材ではDjangoを用いてAmazonに代表されるECサイトを作成します。Djangoが提供する多くの機能の中でも、主にCBV（クラスベースビュー）を
                            積極的に用いて、書くコードの量をなるべく減らすような設計にしております。Djangoを利用すると言っても同じ機能を実現させるさせるために様々な手段がありますので、
                            この教材が紹介しているやり方が正解だとは思わず、選択肢の一つとして受け入れていただければと思います。
                            人のやり方やコードをうまく取り入れる（パクる）ことが、実務をこなせるレベルになる最短ルートだと私は考えておりますので、
                            是非ここで学んだ実装方法を積極的に活用いただけると嬉しいです。
                        </p> 
                    </article>
                </div>
            </div>
        
        </div> <!-- container .//  -->
    </section>
{% endblock %}
<!-- [2-5] ベーステンプレート読み込み追加　ここまで -->

amazon/templates/amazon/sign_up.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" >
    <title>title here</title>

</head>
<body style="background: #81D8D0">
    <div class="container" style="padding: 2rem">
        <div class="row">
            <div class="col-md-6 offset-md-3 col-12">
                <div class="card bg-light">
                    <div class="card-body mx-auto">
                        <form method="POST" action="">
                            {{ form.non_field_errors }}
                            <ul class="messages">
                            {% for message in messages %}
                                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                            {% endfor %}
                            </ul>
                            {% csrf_token %}
                            <div class="form-group input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"> <i class="fa fa-envelope"></i> </span>
                                    </div>
                                    {{ form.email }}
                                    
                            </div> <!-- form-group// -->
                            {{ form.email.errors }}
                            <div class="form-group input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"> <i class="fa fa-user"></i> </span>
                                    </div>
                                    {{ form.name }}
                            </div> <!-- form-group// -->
                            {{ form.name.errors }}
                            <div class="form-group input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
                                </div>
                                {{ form.password1 }}
                                
                            </div> <!-- form-group// -->
                            {{ form.password1.errors }}
                            <div class="form-group input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
                                </div>
                                {{ form.password2 }}
                                
                            </div> <!-- form-group// -->                                      
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary btn-block"> Create Account  </button>
                            </div> <!-- form-group// -->   
                            {{ form.password2.errors }}   
                            <p class="text-center">アカウントをお持ちですか? <a href="{% url 'amazon:login' %}">Log In</a> </p>                                                                 
                        </form>
                    </div>
                </div> <!-- card.// -->
            </div>
        </div>
    </div> <!-- container -->
</body>

amazon/templates/amazon/sign_up_done.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" ></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">
    <title>title here</title>

</head>
<body>
        <div class="jumbotron text-xs-center">
            <h1 class="display-3">Thank You!</h1>
                <p class="lead"><strong>Enjoy shopping!</strong> </p>
            <hr>
            <a class="btn btn-success" href="{% url 'amazon:login' %}">login</a>
        </div>
            
</body>
</html>